config/routes.rb
Rails.application.routes.draw do
  get 'play_logs/index'
  get 'play_logs/show'
  get 'play_logs/edit'
  get 'play_logs/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'play_logs#index'

  resources :users
  resources :play_logs
  resources :games
  resources :hardwares
  resources :manufacturers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/hardware.rb
class Hardware < ApplicationRecord
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/models/play_log.rb
class PlayLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def new
	end

	def create
	end
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
end

app/controllers/play_logs_controller.rb
class PlayLogsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  	@play_log = PrayLog.new
  end

  def create
  	@play_log = PrayLog.new(play_log_params)
  	if @play_log.save
		flash[:notice] = "記録を投稿しました"
	    redirect_to admins_product_path(@product)
	else
		flash[:alert] = "記録の投稿に失敗しました"
		render :new
	end
  end

	protected

	def play_log_params
		params.require(:play_log).permit(:title, :introduction, :user_id, :game_id)
	end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def user_params
        params.require(:user).permit(:nick_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/play_logs_helper.rb
module PlayLogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelrecords</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-default", style="background-color: black;border-color: white;padding: 0 0 0 0;">
    <div class="container">
    <div class="row">
    <div class="col-md-12">


    <% if user_signed_in? %>
           <div class="center-block" style="padding: 0 0 25px 0;">
             <nav class="nav navbar-nav navbar-left" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                <%=link_to root_path, :style=>"color:#777;text-decoration: none;" do %>
                   <h1>TravelRecords</h1>
                <% end %>
             </nav>
             </div>


              <nav class="nav navbar-nav navbar-right" style="padding: 0 0 0 0;">
              <div id="slidemenu">
                <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn" style="padding: 0 0 0 0;" >
                    <li>
                      <%= link_to 'レビューを書く', new_play_log_path, style: "padding: 0 0 0 0;" %>
                    </li>
                    <li>
                      <%= link_to 'ログアウト', destroy_user_session_path, style: "padding: 0 0 0 0;", method: :delete %>
                    </li>
                </ul>
              </div>
            </nav>

    <% else %>
      <div class="center-block" style="padding: 0 0 25px 0;">
        <nav class="nav navbar-nav navbar-left" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn" style="margin-right: 50px;">
        <%=link_to root_path, :style=>"color:#777;text-decoration: none;" do %>
        <h1>TravelRecords</h1>
        <% end %>
        </nav>
      </div>

             <nav class="nav navbar-nav navbar-center" style="padding: 0 0 0 0;">

        </nav>
       <nav class="nav navbar-nav navbar-right" style="margin-left: 50px;padding: 0 0 0 0;">
       <div id="slidemenu">
         <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn" style="padding: 0 0 0 0;" >
              <li>
               <%= link_to 'ログイン', new_user_session_path, style: "padding: 0 15px 0 15px;" %>,
             </li>
            <li>
               <%= link_to '会員登録', new_user_registration_path, style: "padding: 0 15px 0 15px;" %>,
             </li>
          </ul>
        </div>
        </nav>
      <% end %>
    </div>
    </div>
    </div>
    </header>

    <div class="wrapper">
       <%= yield %>
    </div>

  </body>

</html>